### ISSUE TITLE
Check if notify-send exists

### ISSUE THREAD

**Issue by kevinywlui** [kevinywlui/zlong_alert.zsh#1]

**Comment by kevinywlui** [comment]
Solved with 49e3aa88bca8933d347fb44612adee9b5b3afea8

**Comment by deseven** [comment]
Can't notify-send just be optional? I have many headless servers without it and my terminal emulator is configured to notify me about bells. Right now i have this echo you added every time i log in (and also error `command not found: notify-send` after every timely command).

**Comment by kevinywlui** [comment]
Sure. I'll change it by tonight.

**Comment by kevinywlui** [comment]
> Can't notify-send just be optional? I have many headless servers without it and my terminal emulator is configured to notify me about bells. Right now i have this echo you added every time i log in (and also error `command not found: notify-send` after every timely command).

I just fixed changed it in the master branch. You're totally right that it should be optional, I can see how annoying it probably was before. Thanks for the feedback! :smile:

**Comment by deseven** [comment]
Awesome solution! Thanks!
