### ISSUE TITLE
Transfer stewardship of this repo

### ISSUE THREAD

**Issue by kevinywlui** [kevinywlui/zlong_alert.zsh#11]
I haven't been a good steward of this repo (due to work getting busy) and should transfer it.

**Comment by kevinywlui** [comment]
@chrisrhayden Would you be interested in taking over?

**Comment by chrisrhayden** [comment]
I don't think you've done a bad job, but if you're too busy I understand.

I don't mind taking over if you'd like, you could add me as a collaborator
if you want to keep using this repo or add a  depreciated message and a
link to my fork. Whatever works for you.

**Comment by kevinywlui** [comment]
Added you as a collaborator. There's also the possibility of the [actual transfer](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) mechanism, but currently there's a name conflict stopping this.

**Comment by chrisrhayden** [comment]
thanks, I removed the repo if you want to still want to transfer the project, but its up to you

**Comment by kevinywlui** [comment]
Transferred! Best of luck and thanks for all the help.
