### ISSUE TITLE
Commands from remote shell

### ISSUE THREAD

**Issue by henriquenunez** [kevinywlui/zlong_alert.zsh#12]
Hello! Nice repo and functionality!

I was wondering if there could be any support for temrminal sessions running on remote servers, and if it would be too complicated  to make work.

I am willing to make a PR if it's feasible.

Any ideas?

**Comment by chrisrhayden** [comment]
PRs are very welcome 

> Any ideas?

nothing comes to mind but ill look in to it this monday

**Comment by chrisrhayden** [comment]
You can tunnel back to the local machine with ssh.

https://www.ssh.com/academy/ssh/tunneling-example

Though you will have to invoke the session in a particular way, if we add this feature I think we should also add how to set it up in the readme. There is also a security concern with opening a tunnel to the local machine. Though I'm unsure how big a concern it is, I cant say I know all that much about network security.

This plugin is very simple and just hooks in to `preexec` and `precmd`. This means that we would require the user to use zsh on the remote machine and install this plugin.

I think for anything more advance a new project should be made and let this one stay very simple. I would be happy to add an alternatives section to the readme, I'm sure some already exists.

**Comment by henriquenunez** [comment]
That's interesting, I will surely check the alternative projects and if there's not something similar to what I proposed, I will try to develop something in these lines.
