### ISSUE TITLE
Add to the AUR

### ISSUE THREAD

**Issue by bd-g** [kevinywlui/zlong_alert.zsh#26]
This isn't really an issue per say, but just want to get into contact with @kevinywlui .

First of all, great plugin! I love it! I use Arch Linux and like to add everything on my system through my package manager, so I wrote a PKGBUILD for Arch and put it on the AUR so anyone can use it (https://aur.archlinux.org/packages/zlong-alert-git). I'm listed as the maintainer there. If you want to take it over just let me know, it just tracks this git repo.

Feel free to close this issue whenever you want.

**Comment by chrisrhayden** [comment]
Sorry I missed this, it looks good, If you want to stop maintaining make an issue or pr with the pkgbuild.
