### ISSUE TITLE
commands that start with a space (or spaces) do not work

### ISSUE THREAD

**Issue by chrisrhayden** [kevinywlui/zlong_alert.zsh#3]
```bash
# does work
for i in {0..15}; do sleep 1; echo "$i"; done

# does not work
    for i in {0..15}; do sleep 1; echo "$i"; done
```

Commands that start with a space get ignored because of how the cut command on line 43 works

https://github.com/kevinywlui/zlong_alert.zsh/blob/c3e6315311b1ef6e563af6add677f8b55f65c04c/zlong_alert.zsh#L43

switching to `awk '{print $1}'` should work but space is usually a way to ignore things so maybe adding an option could be cool.

```bash
echo 'command foo bar' | awk '{print $1}'
# -> command

echo '    for i in {0..15}; do sleep 1; echo "$i"; done' | awk '{print $1}'
# -> for

echo ' command  foo    bar thing' | awk '{print $1}'
# -> command
```

**Comment by kevinywlui** [comment]
Oh wow. I don't think I even thought about leading spaces. I'm fine with either ignoring or not ignoring be the default as long as there's an option to toggle it.

Would you want to submit a PR? It might be awhile before I get to it.

**Comment by chrisrhayden** [comment]
I can make a PR shortly.

Just as an aside I found the issue from this repo

https://github.com/marzocchi/zsh-notify/pull/80

**Comment by kevinywlui** [comment]
Now fixed thanks to https://github.com/kevinywlui/zlong_alert.zsh/pull/4
